#!/bin/sh

awsRegion=${AWS_REGION}
awsKey=${AWS_KEY}
awsSecret=${AWS_SECRET}

if [ -z "$awsKey" ]; then
    echo "AWS_KEY environment variable is required"
    exit 1
fi

if [ -z "$awsSecret" ]; then
    echo "AWS_SECRET environment variable is required"
    exit 1
fi

mkdir -p ~/.aws

printf "[default]\nregion = %s" "$awsRegion" > ~/.aws/config
printf "[default]\naws_secret_access_key = %s\naws_access_key_id = %s" "$awsSecret" "$awsKey" > ~/.aws/credentials
